---
version: "3.2"
services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_nfs:/data
      - minio_nfs:/certs
    networks:
      - traefik
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DOMAIN=minio.hogin.pro
      - MINIO_SERVER_URL=https://minio.hogin.pro
      - MINIO_BROWSER_REDIRECT_URL=https://console.minio.hogin.pro
    labels:
     - "traefik.enable=true"
     # Console
     - "traefik.http.routers.minio-console.rule=Host(`console.minio.hogin.pro`)"
     - "traefik.http.routers.minio-console.entrypoints=websecure"
     - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
     - "traefik.http.routers.minio-console.service=minio-console"
     - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
     # APi
     - "traefik.http.routers.minio.rule=Host(`minio.hogin.pro`)"
     - "traefik.http.routers.minio.entrypoints=websecure"
     - "traefik.http.routers.minio.tls.certresolver=myresolver"
     - "traefik.http.routers.minio.service=minio"
     - "traefik.http.services.minio.loadbalancer.server.port=9000"

networks:
  traefik:
    name: traefik

volumes:
  minio_nfs:
    name: minio_nfs
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.79,rw"
      device: ":/mnt/Home/minio"
